### ISSUE TITLE
Experiment on different grid sizes & CNN architectures

### ISSUE THREAD

**Issue by sergiuiacob1** [sergiuiacob1/iClicker#2]
1. Parametrise the grid size
2. Train CNN on faces & eye strips for 2x2, 3x3, 4x4, ... grid sizes
4. Experiment with the CNN architecture (no. of layers, no. of convolution filters)
5. Document results: each CNN architecture with each grid size, accuracy graphs for train&test datasets

**Comment by sergiuiacob1** [comment]
1 is done. grid can now be parametrised and predictions can be done on different grid sizes

**Comment by sergiuiacob1** [comment]
Experiments with MLP done.

**Comment by mbilasco** [comment]
Great !

Results were ? On wiki ?

**Comment by sergiuiacob1** [comment]
Yes, for MLP [here](https://github.com/sergiuiacob1/iClicker/wiki/Experiments-using-MLP) and for CNN [here](https://github.com/sergiuiacob1/iClicker/wiki/Experiments-using-CNN).
Some experiments are still ongoing, so the wiki pages aren't finished.

I'm trying to find out which architecture is best (MLP/CNN) and on which dataset they do best. Afterwards, I'll take that combination (so far CNN + extracted eyes) and try to "tweak" the network architecture, tune the hyperparameters, maybe also make the dataset larger and diversify it a little bit to see how far I can go with the predictions.

! Please note that the tables in the wiki pages have multiple columns and they might not be visible at first glance. Make sure you scroll horizontally on them.
