### ISSUE TITLE
Pupil detection/localization

### ISSUE THREAD

**Issue by mbilasco** [sergiuiacob1/iClicker#3]
Datasets 
* hard one : https://dl.acm.org/doi/10.1145/2857491.2857520  - https://arxiv.org/abs/1511.05768
* easy one : http://cs.uef.fi/pupoint/ - http://cs.uef.fi/pupoint/crowdpupil/crowdpupil.zip

**Comment by mbilasco** [comment]
I've started creating the issue, not to lose the pointers to the datasets. please update the issue later and configure it better (milestone, labels, etc...)

**Comment by sergiuiacob1** [comment]
Steps:
1. Derive heatmaps from eye images (crowdpupil)
2. Use the Encoder-Decoder architecture in an attempt to reconstruct the "true" heatmaps. Start with [this](https://github.com/udacity/deep-learning-v2-pytorch/tree/master/autoencoder/convolutional-autoencoder) architecture
3. Extract the landmark position (eye center) from the heatmap and see how it behaves "in the wild"
4. Place the eye's center position in the eye bounding box. Based on the eye center's relative position to this box, predict where the user is looking on a 2x2 and 3x3 grid
